from django.urls import path
from . import views
from .views import search_results
from .views import get_data
from .views import post_meep

urlpatterns = [
    path('', views.home, name="home"),
    path('profile_list/', views.profile_list, name='profile_list'),
    path('profile/<int:pk>/', views.profile, name='profile'),
    path('profile/followers/<int:pk>', views.followers, name='followers'),
    path('profile/follows/<int:pk>', views.follow, name='follows'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.register_user, name='register'),
    path('update_user/', views.update_user, name='update_user'),
    path('meep_like/<int:pk>/', views.meep_like, name='meep_like'), 
    path('meep_show/<int:pk>', views.show_meep, name="meep_show"),
    path('unfollow/<int:pk>', views.unfollow, name="unfollow"),
    path('follow/<int:pk>/', views.follow, name='follow'),
    path('delete_meep/<int:pk>', views.delete_meep, name="delete_meep"),
    path('edit_meep/<int:pk>', views.edit_meep, name="edit_meep"),
    path('search/', views.search, name='search'),
    path('notifications/', views.notifications, name='notifications'),
    path('meep/<int:pk>/', views.show_meep, name='show_meep'),
    path('reply_to_meep/<int:pk>/', views.reply_to_meep, name='reply_to_meep'),
    path('show_meep/<int:pk>/', views.show_meep, name='show_meep'),
    path('show_thread/<int:pk>/', views.show_thread, name='show_thread'),
    path('change_password/', views.change_password, name='change_password'),
    path('trending/', views.trending_topics, name='trending_topics'),
    path('hashtag/<str:hashtag_name>/', views.hashtag_detail, name='hashtag_detail'),
    path('search_explore/', search_results, name='search_explore'),
    path('inbox/', views.inbox_view, name='inbox'),
    path('conversation/<int:user_id>/', views.conversation_view, name='conversation_view'),
    path('send_message/<int:recipient_id>/', views.send_message, name='send_message'),
    path('data/', get_data, name='get_data'),
    path('post_meep/', post_meep, name='post_meep'),
    path('live_search/', views.live_search, name='live_search'),
    path('notifications/fetch/', views.fetch_notifications, name='fetch_notifications'),
    path('toggle-follow/<int:pk>/', views.toggle_follow, name='toggle_follow'),
    path('send-message-ajax/<int:recipient_id>/', views.send_message_ajax, name='send_message_ajax'),
    path('fetch-new-messages/<int:conversation_with>/', views.fetch_new_messages, name='fetch_new_messages'),
    path('messages/unread_count/', views.unread_message_count, name='unread_message_count'),
    path('messages/unread_counts/', views.unread_conversation_counts, name='unread_conversation_counts'),
     path('profile/<int:user_id>/followers/', views.followers_list, name='followers_list'),
    path('profile/<int:user_id>/following/', views.following_list, name='following_list'),
     path('ad_click/<int:ad_id>/', views.track_ad_click, name='track_ad_click'),
]
