# Generated by Django 4.2.4 on 2024-08-23 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('musker', '0008_alter_profile_date_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meep',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='meep',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='meep_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meep',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='musker.meep')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
