# Generated by Django 4.2.4 on 2024-08-23 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musker', '0009_alter_meep_body_alter_meep_likes_alter_meep_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meep',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='musker.meep'),
        ),
    ]
