# Generated by Django 4.2.4 on 2024-08-24 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musker', '0010_meep_reply_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
