# Generated by Django 4.2.4 on 2024-08-25 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musker', '0014_poll_polloption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meep',
            name='hashtags',
        ),
        migrations.RemoveField(
            model_name='meep',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='meep',
            name='reply_to',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='created_by',
        ),
        migrations.AddField(
            model_name='meep',
            name='poll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meeps', to='musker.poll'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='meep',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='associated_poll', to='musker.meep'),
        ),
    ]
