# Generated by Django 4.2.4 on 2024-08-25 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('musker', '0015_remove_meep_hashtags_remove_meep_likes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polloption',
            name='poll',
        ),
        migrations.RemoveField(
            model_name='polloption',
            name='votes',
        ),
        migrations.RemoveField(
            model_name='meep',
            name='poll',
        ),
        migrations.AddField(
            model_name='meep',
            name='hashtags',
            field=models.ManyToManyField(blank=True, related_name='meeps', to='musker.hashtag'),
        ),
        migrations.AddField(
            model_name='meep',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='meep_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meep',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='musker.meep'),
        ),
        migrations.DeleteModel(
            name='Poll',
        ),
        migrations.DeleteModel(
            name='PollOption',
        ),
    ]
