# Generated by Django 4.2.4 on 2024-08-27 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musker', '0017_notification_meep_notification_related_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hashtag',
            name='usage_count',
        ),
        migrations.AddField(
            model_name='hashtag',
            name='total_meeps',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hashtag',
            name='trending',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
